import "std2"

namespace Prog {

	type MyErr is error {
		int a
		string Msg get return "MyErr"
	}

	void Foo() {
		try {
			error err ≡ new MyErr
			throw err
			Std.PrintDLn(123)
		} catch {
			Std.PrintS("caught #1: ")
			Std.PrintC('"')
			Std.PrintS(caught.Msg)
			Std.PrintCLn('"')
		}

		try {
			int@ a ≡ null
			@a ≡ 10
		} catch {
			Std.PrintS("caught #2: ")
			Std.PrintC('"')
			Std.PrintS(caught.Msg)
			Std.PrintCLn('"')
		}

		int@ a ≡ null
		try @a ≡ 10 catch {
			Std.PrintS("caught #3: ")
			Std.PrintC('"')
			Std.PrintS(caught.Msg)
			Std.PrintCLn('"')
		}
	}

	void Main() {
		Foo()
		Std.PrintSLn("success!")
	}
}